server:
  port: 8081

spring:
  application:
    name: ProductService
  config:
    import: "configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: ConfigServer